"use client";

// import { Inter } from "next/font/google";
// import "./globals.css";
import Navbar from "@/components/Navbar";
// import { Providers } from "./providers";
import Footer from "@/components/Footer";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Pharmapedia",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         <Providers>
//           <Navbar />
//           {children}
//           <Footer />
//         </Providers>
//       </body>
//     </html>
//   );
// }
// components/ClientWrapper.js


import { Inter } from "next/font/google";
import "./globals.css";
import { usePathname } from "next/navigation";
import { ToastContainer } from "react-toastify";
const inter = Inter({ subsets: ["latin"] });

const ClientWrapper = ({ children }) => {
  const currentRoute = usePathname();

  // Define the regex pattern for routes starting with /AdminDashboard/
  const adminDashboardRegex = /^\/Dashboard\//;

  // Check if the current route matches the AdminDashboard pattern
  const shouldRenderHeaderFooter = !adminDashboardRegex.test(currentRoute);

  return (
    <html lang="en">
      <body className={inter.className}>
        {shouldRenderHeaderFooter && <Navbar />}
        <ToastContainer />
        {children}
        {shouldRenderHeaderFooter && <Footer />}
      </body>
    </html>
  );
};

export default ClientWrapper;